### ISSUE TITLE
Naming runs with multiline text crashes

### ISSUE THREAD

**Issue by nelsonth** [ldevesine/cscibox#24]
Right-click a run, choose "rename", then add multiple lines of text.

Traceback (most recent call last):
  File "/Users/lizb/Calvin/src/cscience/GUI/Editors/CoreBrowser.py", line 573, in on_repository_altered
    self.update_runs()
  File "/Users/lizb/Calvin/src/cscience/GUI/Editors/CoreBrowser.py", line 737, in update_runs
    run_id = self.runlist.AppendItem(newroot, run.display_name, ct_type=1)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/lib/agw/customtreectrl.py", line 5138, in AppendItem
    return self.DoInsertItem(parent, len(parent.GetChildren()), text, ct_type, wnd, image, selImage, data)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/lib/agw/customtreectrl.py", line 4886, in DoInsertItem
    raise Exception("\nERROR: In Order To Append/Insert A MultiLine Text You Have To Use The Style TR_HAS_VARIABLE_ROW_HEIGHT")
Exception: 
ERROR: In Order To Append/Insert A MultiLine Text You Have To Use The Style TR_HAS_VARIABLE_ROW_HEIGHT
Traceback (most recent call last):
  File "/Users/lizb/Calvin/src/cscience/GUI/Editors/CoreBrowser.py", line 573, in on_repository_altered
    self.update_runs()
  File "/Users/lizb/Calvin/src/cscience/GUI/Editors/CoreBrowser.py", line 737, in update_runs
    run_id = self.runlist.AppendItem(newroot, run.display_name, ct_type=1)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/lib/agw/customtreectrl.py", line 5138, in AppendItem
    return self.DoInsertItem(parent, len(parent.GetChildren()), text, ct_type, wnd, image, selImage, data)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/lib/agw/customtreectrl.py", line 4886, in DoInsertItem
    raise Exception("\nERROR: In Order To Append/Insert A MultiLine Text You Have To Use The Style TR_HAS_VARIABLE_ROW_HEIGHT")
Exception: 
ERROR: In Order To Append/Insert A MultiLine Text You Have To Use The Style TR_HAS_VARIABLE_ROW_HEIGHT

This should just require changing the rename box to a single-line text field.

**Comment by nelsonth** [comment]
This doesn't crash any more, but it does look REALLY ugly if you assign a multiline name.  Closed for now.
